name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: permission-element.bs
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: geolocation-element.bs
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
  copy_demo:
    name: Copy demo page to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          branches: gh-pages
          files: demo/geolocation_mock.html polyfills/
